version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: laravel_orion_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: OrionGym
      MYSQL_ROOT_PASSWORD: Admin23#
      MYSQL_PASSWORD: Admin23#
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
